version: "3.7"

services:
  web:
    build: docker/web
    expose:
      - 9003
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/
    environment:
      XDEBUG_MODE: develop,debug
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - composer
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
            - ./docker/init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER}

      
  composer:
    build: docker/composer
    # user: $UID
    volumes:
      - ./:/app
    command: composer install
    environment:
      - HOME=/home/composer
    working_dir: /app
    
  # phpmyadmin:
  #     image: phpmyadmin/phpmyadmin
  #     container_name: pma
  #     links:
  #       - mysql
  #     environment:
  #       PMA_HOST: mysql
  #       PMA_PORT: 3306
  #       PMA_ARBITRARY: 1
  #     restart: always
  #     ports:
  #       - 8081:80

      